name: WG152ExtraFlags
version: ${project.version}
main: br.com.devmastersouza.wgextraflags.WG152ExtraFlags
depend: [WorldGuard]
authors: [DevMasterSouza]
description: adiciona algumas flags novas do WG na 1.5.2 entre outras
website: https://github.com/DevMasterSouza/WG152ExtraFlags
